services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  crawler:
    build:
      context: ./crawler
    ports:
      - "6789:6789"

volumes:
  n8n_data:

